project_id = "vsemrziqxrrfcquxfnwd"

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-callback]
verify_jwt = false

[functions.shopify-order-webhook]
verify_jwt = false

[functions.get-og-metadata]
verify_jwt = false

[functions.ogmetadata]
verify_jwt = false

[functions.fetch-public-spotify-data]
verify_jwt = false

[functions.healthcheck]
verify_jwt = false

[functions.meta-conversions]
verify_jwt = false

[functions.project-stats]
verify_jwt = false

[functions.instagram-messaging]
verify_jwt = false

[functions.youtube-stats]
verify_jwt = false

[functions.youtube-auth]
verify_jwt = false

[functions.youtube-callback]
verify_jwt = false
